### ISSUE TITLE
camel case in parameter names

### ISSUE THREAD

**Issue by GregorDeCillia** [R-package/styledTables#7]
`devtools::lint()` reveals that there are some parameter names left that use camelCase. In my opinion, these should be replaced with snake_case alternatives. This will break some public API, so if we do this it should happen before the CRAN release.

https://github.com/R-package/styledTables/blob/90df70a65c02be7b772d0c4768e90a2944221efa/R/alignment.R#L8-L11

**Comment by a-maldet** [comment]
Removed all functions that were not meant for the package API from the NAMESPACE. [a3b8cb7d316f6a4f597f03961f54200605a998a7](a3b8cb7d316f6a4f597f03961f54200605a998a7)
